version: "3"
services:
  web:
    build: .
    ports:
      # default port 5000, just in case it's conflict with local port in Mac
      - "8088:5000"
    command:
      - flask
      - run
    environment:
      - FLASK_ENV=development
    volumes:
      - ~/.aws:/root/.aws
      - .:/usr/src/app/
      - logvolume01:/var/log
volumes:
  logvolume01: {}