apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend-image
        imagePullPolicy: Always
        command:
          - flask
          - run
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: 
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 512Mi
      restartPolicy: Always
      serviceAccountName: backend-app
      # ensure evenly spread across multi-AZ
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            foo: backend
      # if want to spread across the node as well
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            foo: backend