apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: backend
  name: backend-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # image: 414879998402.dkr.ecr.ap-southeast-1.amazonaws.com/ssa-demo-backend:52c4fbb
        image: backend-image
        imagePullPolicy: Always
        command:
          - flask
          - run
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: 
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 512Mi
      restartPolicy: Always
      serviceAccountName: backend-app
      imagePullSecrets: 
      - name: ecr-login