apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend-app
  namespace: default
spec:
  ports:
  - name: https
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: backend
  type: ClusterIP
